# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WgeO_4sMKtBaqCh8DWc8z79MkwaR_NF
"""

# !pip install gradio

import gradio as gr
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the model and vectorizer
with open('model.pkl', 'rb') as model_file:
  model = pickle.load(model_file)

with open('vectorizer.pkl', 'rb') as vectorizer_file:
  tf_idf = pickle.load(vectorizer_file)

# Define the prediction function
def predict_spam(message):
  transformed_message = tf_idf.transform([message]).toarray()
  prediction = model.predict(transformed_message)
  return "Not Spam" if prediction[0] == 0 else "Spam"

# Create the Gradio interface
iface = gr.Interface(
    fn=predict_spam,
    inputs=gr.Textbox(lines=2, placeholder="Enter SMS Text..."),
    outputs=gr.Textbox(),
    title="SMS Spam Detector",
    description="Enter an SMS message to determine if it's Spam or Not Spam."
)

# Launch the interface
iface.launch()

